"""
Test
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum

from hooks.coalesce_hook import CoalesceHook
import os

@aql.dataframe(task_id="python_1")
def python_1_func():
    #hook = coalesce_hook("coalesce_default","snowflake_default")
    print(os.listdir('include'))

default_args={
    "owner": "Mark Van Der Heijden,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2024-12-04", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Mark Van Der Heijden": "mailto:mark@coalesce.io",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm4714fyp167k01o6erwcqyvw/cloud-ide/cm4723jni163m01nlk8y2ltgu/cm49qc3wp1o6b01o6r5gzjsi0",
    },
)
def Test():
    python_1 = python_1_func()

dag_obj = Test()
